services:
  postgres:
    image: postgres:16-alpine
    container_name: shared-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-db-network

networks:
  shared-db-network:
    name: shared-db-network

volumes:
  postgres_data:
    name: shared-postgres-data
